AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConnectorId:
    Type: String
Resources:
  TransferExecutor:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/transfer-executor.json
      DefinitionSubstitutions:
        StatusTableName: !Ref TransferStatusTable
        ConnectorId: !Ref ConnectorId
        BucketName: !Ref DataBucket
        S3Path: "dest"
      Role: !GetAtt TransferExecuterStateMachineRole.Arn
      Events:
        DaylySchedule:
          Type: Schedule 
          Properties:
            Description: Run everyday
            Schedule: "rate(1 day)"
  TransferStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "TransferStatus"
          AttributeType: "S"
        - AttributeName: "FilePath"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "TransferStatus"
          KeyType: "HASH"
        - AttributeName: "FilePath"
          KeyType: "RANGE"      
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sftp-connector-file-destination-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
  TransferExecuterStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "transfer-execute-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource:
                  - !GetAtt TransferStatusTable.Arn
              - Effect: Allow
                Action: transfer:StartFileTransfer
                Resource:
                  - !Sub arn:aws:transfer:${AWS::Region}:${AWS::AccountId}:connector/${ConnectorId}