AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConnectorId:
    Type: String
Resources:
  #---------------------------------------------
  #---- Transfer Machine
  #---------------------------------------------
  TransferExecutor:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/transfer-executor.json
      DefinitionSubstitutions:
        StatusTableName: !Ref TransferStatusTable
        ConnectorId: !Ref ConnectorId
        BucketName: !Ref DataBucket
        S3Path: "dest"
      Role: !GetAtt TransferExecuterStateMachineRole.Arn
      Events:
        DaylySchedule:
          Type: Schedule 
          Properties:
            Description: Run everyday
            Schedule: "rate(1 day)"
  TransferExecuterStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "transfer-execute-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource:
                  - !GetAtt TransferStatusTable.Arn
              - Effect: Allow
                Action: transfer:StartFileTransfer
                Resource:
                  - !Sub arn:aws:transfer:${AWS::Region}:${AWS::AccountId}:connector/${ConnectorId}
  #---------------------------------------------
  #---- Complete Event Receive Machine
  #---------------------------------------------
  CompleteEventReceiver:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/complete-event-receiver.json
      DefinitionSubstitutions:
        StatusTableName: !Ref TransferStatusTable
        AthenaWorkGroup: !Ref WorkGroup
      Role: !GetAtt CompleteEventReceiverRole.Arn
      Events:
        CompleteEvent:
          Type: EventBridgeRule 
          Properties:
            RuleName: sftp-connector-complete-event-rule
            Target:
              Id: complete-receive-machine
            Pattern:
              source:
                - "aws.transfer"
              detail-type:
                - "SFTP Connector File Retrieve Completed"
              resources:
                - !Sub arn:aws:transfer:${AWS::Region}:${AWS::AccountId}:connector/${ConnectorId}
  CompleteEventReceiverRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "complete-event-receiver-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - dynamodb:PutItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt TransferStatusTable.Arn
              - Effect: Allow
                Action: 
                  - athena:StartQueryExecution
                Resource:
                  - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${WorkGroup}
              - Effect: Allow
                Action: 
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                  - s3:CreateBucket
                  - s3:PutObject"
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub ${DataBucket.Arn}/*

  #---------------------------------------------
  #----　Others
  #---------------------------------------------
  TransferStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "TransferStatus"
          AttributeType: "S"
        - AttributeName: "FilePath"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "TransferStatus"
          KeyType: "HASH"
        - AttributeName: "FilePath"
          KeyType: "RANGE"      
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sftp-connector-file-destination-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
  Database:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: sftp-connector-sample-db
  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref Database
      TableInput:
        Name: sample_table
        TableType: EXTERNAL_TABLE
        Parameters:
          skip.header.line.count: '1'
        StorageDescriptor:
          Columns:
            - Name: id
              Type: Int
            - Name: hash_value
              Type: String
            - Name: created_at
              Type: Timestamp
          Location: !Sub s3://${DataBucket}/dest/
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
            Parameters:
              field.delim: '\t'
  WorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: sftp-connector-sample
      State: ENABLED
      WorkGroupConfigurationUpdates:
        BytesScannedCutoffPerQuery: 10000000
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: false
        ResultConfigurationUpdates:
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
          OutputLocation: !Sub s3://${DataBucket}/summary/