AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConnectorId:
    Type: String
  ReportReceiveAddress:
    Type: String
Resources:
  #---------------------------------------------
  #---- Transfer Machine
  #---------------------------------------------
  TransferExecutor:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: statemachine/transfer-executor.json
      DefinitionSubstitutions:
        StatusTableName: !Ref TransferStatusTable
        ConnectorId: !Ref ConnectorId
        BucketName: !Ref DataBucket
        S3Path: "dest"
      Role: !GetAtt TransferExecuterStateMachineRole.Arn
  TransferExecuterStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "transfer-execute-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource:
                  - !GetAtt TransferStatusTable.Arn
              - Effect: Allow
                Action: transfer:StartFileTransfer
                Resource:
                  - !Sub arn:aws:transfer:${AWS::Region}:${AWS::AccountId}:connector/${ConnectorId}
  #---------------------------------------------
  #---- Complete Event Receive Machine
  #---------------------------------------------
  CompleteEventReceiver:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: statemachine/complete-event-receiver.json
      DefinitionSubstitutions:
        StatusTableName: !Ref TransferStatusTable
        AthenaWorkGroup: !Ref WorkGroup
        GlueDBName: !Ref Database
        GlueTablename: !Ref GlueTable
        DBIndexName: TransferStatus-hash
      Role: !GetAtt CompleteEventReceiverRole.Arn
      Events:
        CompleteEvent:
          Type: EventBridgeRule 
          Properties:
            RuleName: sftp-connector-complete-event-rule
            Target:
              Id: complete-receive-machine
            Pattern:
              source:
                - "aws.transfer"
              detail-type:
                - "SFTP Connector File Retrieve Completed"
              resources:
                - !Sub arn:aws:transfer:${AWS::Region}:${AWS::AccountId}:connector/${ConnectorId}
  CompleteEventReceiverRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "complete-event-receiver-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt TransferStatusTable.Arn
                  - !Sub ${TransferStatusTable.Arn}/index/*
              - Effect: Allow
                Action: 
                  - athena:StartQueryExecution
                Resource:
                  - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${WorkGroup}
              - Effect: Allow
                Action: 
                  - glue:GetDatabase
                  - glue:GetTable
                Resource:
                  - !Sub arn:aws:glue:ap-northeast-1:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:ap-northeast-1:${AWS::AccountId}:database/${Database}
                  - !Sub arn:aws:glue:ap-northeast-1:${AWS::AccountId}:table/${Database}/*
              - Effect: Allow
                Action: 
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                  - s3:CreateBucket
                  - s3:PutObject
                Resource:
                  - !GetAtt DataBucket.Arn
                  - !Sub ${DataBucket.Arn}/*
  #---------------------------------------------
  #---- Athena Report Machine
  #---------------------------------------------
  AthenaResultReportMachine:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: statemachine/athena-result-repoter.json
      DefinitionSubstitutions:
        SnsTopicArn: !Ref AthenaReportTopic
        BucketName: !Ref DataBucket
        OutputPrefix: summary/
      Role: !GetAtt AthenaResultReportMachineRole.Arn
      Events:
        CompleteEvent:
          Type: EventBridgeRule 
          Properties:
            RuleName: sftp-connector-result-report-rule
            Target:
              Id: complete-receive-machine
            Pattern:
              source:
                - "aws.athena"
              detail-type:
                - "Athena Query State Change"
              detail:
                currentState:
                  - "SUCCEEDED"
                workgroupName: 
                  - !Ref WorkGroup
  AthenaResultReportMachineRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: states.amazonaws.com
      Policies:
        - PolicyName: "complete-event-receiver-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - s3:GetObject
                Resource:
                  - !Sub ${DataBucket.Arn}/summary/*
              - Effect: Allow
                Action: 
                  - sns:Publish
                Resource:
                  - !Ref AthenaReportTopic
              - Effect: Allow
                Action: 
                  - athena:GetQueryExecution
                Resource:
                  - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${WorkGroup}
  AthenaReportTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        - !Ref AthenaReportTopic
  AthenaReportTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: sftp-connecter-result-report
      DisplayName: sftp-connecter-result-report
  AthenaReportSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AthenaReportTopic
      Protocol: email
      Endpoint: !Ref ReportReceiveAddress
  #---------------------------------------------
  #----　Others
  #---------------------------------------------
  TransferStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "FilePath"
          AttributeType: "S"
        - AttributeName: "TransferStatus"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "FilePath"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "TransferStatus-hash"
          KeySchema:
            - AttributeName: "TransferStatus"
              KeyType: "HASH"
            - AttributeName: "FilePath"
              KeyType: "RANGE"
          Projection:
            ProjectionType: KEYS_ONLY
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub sftp-connector-file-destination-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
  Database:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: sftp-connector-sample-db
  GlueTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref Database
      TableInput:
        Name: sample_table
        TableType: EXTERNAL_TABLE
        StorageDescriptor:
          Columns:
            - Name: id
              Type: Int
            - Name: hash_value
              Type: String
            - Name: created_at
              Type: Timestamp
          Location: !Sub s3://${DataBucket}/dest/
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
            Parameters:
              field.delim: "\t"
  WorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: sftp-connector-sample
      State: ENABLED
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 10000000
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: false
        RequesterPaysEnabled: false
        ResultConfiguration:
          EncryptionConfiguration:
            EncryptionOption: SSE_S3
          OutputLocation: !Sub s3://${DataBucket}/summary/